### ISSUE TITLE
Chrome version not found

### ISSUE THREAD

**Issue by mIcHyAmRaNe** [weskerfoot/DeleteFB#126]
### Error

```
➜ deletefb -E "email" -P "password" -U "https://www.facebook.com/username" -H
                           
Traceback (most recent call last):
  File "/home/yasuo/.local/bin/deletefb", line 11, in <module>
    sys.exit(run_delete())
  File "/home/yasuo/.local/lib/python3.6/site-packages/deletefb/deletefb.py", line 117, in run_delete
    chrome_binary_path=args.chromebin
  File "/home/yasuo/.local/lib/python3.6/site-packages/deletefb/tools/login.py", line 44, in login
    driver = setup_selenium(chrome_options, chrome_binary_path)
  File "/home/yasuo/.local/lib/python3.6/site-packages/deletefb/tools/chrome_driver.py", line 64, in setup_selenium
    driver_path = get_webdriver(chrome_binary_path)
  File "/home/yasuo/.local/lib/python3.6/site-packages/deletefb/tools/chrome_driver.py", line 121, in get_webdriver
    chrome_maj_version, chrome_webdriver = construct_driver_url(chrome_binary_path)
  File "/home/starlab/.local/lib/python3.6/site-packages/deletefb/tools/chrome_driver.py", line 100, in construct_driver_url
    raise ChromeError("Chrome version not found")
deletefb.exceptions.ChromeError: Chrome version not found
```
### chrome driver

```
➜ sudo apt install chromium-chromedriver                                                                      

Reading package lists... Done
Building dependency tree       
Reading state information... Done
chromium-chromedriver is already the newest version (80.0.3987.149-0ubuntu0.18.04.1).
```

### chrome version: 
Version 73.0.3683.86 (Official Build) Built on Ubuntu , running on elementary 5.0 (64-bit)

why the scirpt doesn't find chrome version? i have chromedriver and chromium-browser in my path 
Have i to update chrome? 

#### update
have same problem even after updating chrome to `Version 80.0.3987.149 (Official Build) Built on Ubuntu , running on elementary 5.0 (64-bit)`

in my `/usr/bin/` folder i have 2 files relate to chrome : `chromium-browser` and `chromdriver`
perhaps the script doesn't recognize the name to get the version from them? 

```
/usr/bin  
➜ chromium-browser --version
Chromium 80.0.3987.149 Built on Ubuntu , running on elementary 5.0

➜ chromedriver --version
ChromeDriver 80.0.3987.149 (5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16})
```

**Comment by mIcHyAmRaNe** [comment]
i think you have to add ```chromium-browser``` to this line : [line](https://github.com/weskerfoot/DeleteFB/blob/master/deletefb/tools/chrome_driver.py#L81)

i don't know if you should add it in other place for that i don't create a PR

**Comment by weskerfoot** [comment]
> i think you have to add `chromium-browser` to this line : [chrome_driver.py](https://github.com/weskerfoot/DeleteFB/blob/master/deletefb/tools/chrome_driver.py#L81)
> 
> i don't know if you should add it in other place for that i don't create a PR

Yes, that's the solution. I'll make a PR.

**Comment by weskerfoot** [comment]
It should be fixed now. I'll do a release to PyPI in a little while. You can run it from `master` right now.

**Comment by weskerfoot** [comment]
Fixed. Run `pip install --user delete-facebook-posts==1.1.14` to get the new release.

**Comment by incubo4u** [comment]
i have the same problem running the version 1.1.17 



Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/mikolajkozakiewicz/Desktop/DeleteFB/deletefb/deletefb.py", line 143, in <module>
    run_delete()
  File "/Users/mikolajkozakiewicz/Desktop/DeleteFB/deletefb/deletefb.py", line 112, in run_delete
    driver = login(
  File "/Users/mikolajkozakiewicz/Desktop/DeleteFB/deletefb/tools/login.py", line 44, in login
    driver = setup_selenium(chrome_options, chrome_binary_path)
  File "/Users/mikolajkozakiewicz/Desktop/DeleteFB/deletefb/tools/chrome_driver.py", line 69, in setup_selenium
    driver_path = get_webdriver(chrome_binary_path)
  File "/Users/mikolajkozakiewicz/Desktop/DeleteFB/deletefb/tools/chrome_driver.py", line 125, in get_webdriver
    chrome_maj_version, chrome_webdriver = construct_driver_url(chrome_binary_path)
  File "/Users/mikolajkozakiewicz/Desktop/DeleteFB/deletefb/tools/chrome_driver.py", line 104, in construct_driver_url
    raise ChromeError("Chrome version not found")
deletefb.exceptions.ChromeError: Chrome version not found

**Comment by incubo4u** [comment]
the docker version  also fails to deal with chromedriver



Downloading Chrome Webdriver
100% |#################################################################################################################|
Completed downloading the Chrome Driver.
Traceback (most recent call last):
  File "/home/deletefb/.local/lib/python3.7/site-packages/deletefb/tools/chrome_driver.py", line 66, in setup_selenium
    return webdriver.Chrome(options=options)
  File "/home/deletefb/.local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/deletefb/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/deletefb/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/deletefb/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/deletefb/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/deletefb/.local/lib/python3.7/site-packages/deletefb/deletefb.py", line 143, in <module>
    run_delete()
  File "/home/deletefb/.local/lib/python3.7/site-packages/deletefb/deletefb.py", line 117, in run_delete
    chrome_binary_path=args.chromebin
  File "/home/deletefb/.local/lib/python3.7/site-packages/deletefb/tools/login.py", line 44, in login
    driver = setup_selenium(chrome_options, chrome_binary_path)
  File "/home/deletefb/.local/lib/python3.7/site-packages/deletefb/tools/chrome_driver.py", line 70, in setup_selenium
    return webdriver.Chrome(executable_path=driver_path, options=options)
  File "/home/deletefb/.local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/deletefb/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/deletefb/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/deletefb/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/deletefb/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

make: *** [run] Error 1

**Comment by weskerfoot** [comment]
@incubo4u splitting it off into a new issue
