### ISSUE TITLE
unlike_pages option timing out

### ISSUE THREAD

**Issue by RichardBean** [weskerfoot/DeleteFB#132]
Unlike pages is timing out without doing anything. Could I increase the limit, or maybe start the process from a different URL? Thanks for the app - keeping up with the FB changes must really feel like whack-a-mole!

DevTools listening on ws://127.0.0.1:60570/devtools/browser/46ac20ae-17ff-4429-89d2-8c0b30227c1a
deletefb.tools.likes-ERROR-08:38:02-Traceback of load_likes
Traceback (most recent call last):
  File "C:\Users\rbean\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\deletefb\tools\likes.py", line 26, in load_likes
    wait.until(
  File "C:\Users\rbean\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by weskerfoot** [comment]
This should be fixed in https://github.com/weskerfoot/DeleteFB/pull/134 but still needs a bit of work to make it ignore pages that don't exist anymore

**Comment by weskerfoot** [comment]
should be fixed in the latest HEAD, will release soon
