### ISSUE TITLE
chromedriver issues

### ISSUE THREAD

**Issue by weskerfoot** [weskerfoot/DeleteFB#147]
the docker version  also fails to deal with chromedriver

Downloading Chrome Webdriver
100% |#################################################################################################################|
Completed downloading the Chrome Driver.
Traceback (most recent call last):
  File "/home/deletefb/.local/lib/python3.7/site-packages/deletefb/tools/chrome_driver.py", line 66, in setup_selenium
    return webdriver.Chrome(options=options)
  File "/home/deletefb/.local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/deletefb/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/deletefb/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/deletefb/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/deletefb/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/deletefb/.local/lib/python3.7/site-packages/deletefb/deletefb.py", line 143, in <module>
    run_delete()
  File "/home/deletefb/.local/lib/python3.7/site-packages/deletefb/deletefb.py", line 117, in run_delete
    chrome_binary_path=args.chromebin
  File "/home/deletefb/.local/lib/python3.7/site-packages/deletefb/tools/login.py", line 44, in login
    driver = setup_selenium(chrome_options, chrome_binary_path)
  File "/home/deletefb/.local/lib/python3.7/site-packages/deletefb/tools/chrome_driver.py", line 70, in setup_selenium
    return webdriver.Chrome(executable_path=driver_path, options=options)
  File "/home/deletefb/.local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/deletefb/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/deletefb/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/deletefb/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/deletefb/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

make: *** [run] Error 1

_Originally posted by @incubo4u in https://github.com/weskerfoot/DeleteFB/issues/126#issuecomment-735270075_

**Comment by SeanDS** [comment]
I'm getting this error too with the `wjak56/deletefb:latest` image.
