### ISSUE TITLE
deletefb.exceptions.ChromeError: Chrome version not found

### ISSUE THREAD

**Issue by danielfcastro** [weskerfoot/DeleteFB#153]
I did the install process using first the command 
`pip3 install -r requirements.txt` 
and then 
`pip3 install --user delete-facebook-posts`

When I execute using the command
`deletefb -E 'mymail' -P 'mypassword' -U 'https://www.facebook.com/myprofile/'` I get the error below.

Traceback (most recent call last):
  File "c:\python\python37\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "c:\python\python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "c:\python\python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] O sistema não pode encontrar o arquivo especificado

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dfcas\AppData\Roaming\Python\Python37\site-packages\deletefb\tools\chrome_driver.py", line 66, in setup_selenium
    return webdriver.Chrome(options=options)
  File "c:\python\python37\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "c:\python\python37\lib\site-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\deleteFB\deletefb.exe\__main__.py", line 7, in <module>
  File "C:\Users\dfcas\AppData\Roaming\Python\Python37\site-packages\deletefb\deletefb.py", line 117, in run_delete
    chrome_binary_path=args.chromebin
  File "C:\Users\dfcas\AppData\Roaming\Python\Python37\site-packages\deletefb\tools\login.py", line 44, in login
    driver = setup_selenium(chrome_options, chrome_binary_path)
  File "C:\Users\dfcas\AppData\Roaming\Python\Python37\site-packages\deletefb\tools\chrome_driver.py", line 69, in setup_selenium
    driver_path = get_webdriver(chrome_binary_path)
  File "C:\Users\dfcas\AppData\Roaming\Python\Python37\site-packages\deletefb\tools\chrome_driver.py", line 125, in get_webdriver
    chrome_maj_version, chrome_webdriver = construct_driver_url(chrome_binary_path)
  File "C:\Users\dfcas\AppData\Roaming\Python\Python37\site-packages\deletefb\tools\chrome_driver.py", line 104, in construct_driver_url
    raise ChromeError("Chrome version not found")
deletefb.exceptions.ChromeError: Chrome version not found

**Comment by AlexKalopsia** [comment]
@danielfcastro I am having the same exact issue, would you mind elaborating on how you fixed this issue?

**Comment by AlexKalopsia** [comment]
For whoever might be running into the same issue:

The problem is that DeleteFb can't find the chromium drivers. 

1) Download them from [here](https://chromedriver.chromium.org/downloads)
2) Save them in a directory, ie `C:/bin/chromedrivers/chromedriver.exe`
3) Add the chromium folder to your PATH environment variables. (On windows go on System Properties > Advanced > Environment Variables, then add `C:/bin/chromedrivers/` to the `Path` variable. You might have to restart the system. 

This should be it :)
