### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by sharmashivanand** [weskerfoot/DeleteFB#167]
Tried on Arch, Ubuntu as well as building the docker image. Here's the docker output.

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/deletefb/.local/lib/python3.9/site-packages/deletefb/deletefb.py", line 4, in <module>
    from .tools.likes import unlike_pages
  File "/home/deletefb/.local/lib/python3.9/site-packages/deletefb/tools/likes.py", line 1, in <module>
    from .archive import archiver
  File "/home/deletefb/.local/lib/python3.9/site-packages/deletefb/tools/archive.py", line 8, in <module>
    import cattr
  File "/home/deletefb/.local/lib/python3.9/site-packages/cattr/__init__.py", line 2, in <module>
    from .converters import Converter, UnstructureStrategy
  File "/home/deletefb/.local/lib/python3.9/site-packages/cattr/converters.py", line 15, in <module>
    from ._compat import (
  File "/home/deletefb/.local/lib/python3.9/site-packages/cattr/_compat.py", line 87, in <module>
    from typing import _Union
ImportError: cannot import name '_Union' from 'typing' (/usr/lib/python3.9/typing.py)
```

**Comment by weskerfoot** [comment]
It's a version issue between python 3.9 and 3.8, https://github.com/weskerfoot/DeleteFB/issues/96

Sadly I don't have time to really work on this anymore but if someone wants to refactor it be my guest

**Comment by sharmashivanand** [comment]
I can use any virtual machine and any version of python. Is there any guide which outlines shure-shot steps to get the job done?
