### ISSUE TITLE
Error on OSX

### ISSUE THREAD

**Issue by JoeKlimcak** [weskerfoot/DeleteFB#32]
Running on OSX, running deletefb with the passed parameters produces the following: 

```
> Traceback (most recent call last):
>   File "./deletefb.py", line 139, in <module>
>     run_delete()
>   File "./deletefb.py", line 58, in run_delete
>     is_headless=args.is_headless
>   File "./deletefb.py", line 81, in delete_posts
>     driver = Chrome(options=chrome_options)
>   File "/Users/joe/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
>     self.service.start()
>   File "/Users/joe/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/common/service.py", line 76, in start
>     stdin=PIPE)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
>     errread, errwrite)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
>     raise child_exception
> OSError: [Errno 20] Not a directory
```

Encountered this before?

**Comment by weskerfoot** [comment]
Hi, it looks like an issue with the Chrome driver for Selenium. Can you tell me how you installed the Chrome driver, and what version it is?

If you haven't set it up yet, then I think `brew cask install chromedriver` should get you going. I will add something to the README about MacOS.

**Comment by weskerfoot** [comment]
Better error messages implemented in https://github.com/weskerfoot/DeleteFB/pull/31/commits/fddd373d142a36f0161406b7975fb920632bf88f
