### ISSUE TITLE
after update to 1.1.2, deletefb crash with FileNotFoundError

### ISSUE THREAD

**Issue by dominix** [weskerfoot/DeleteFB#58]
I have just updated to 1.1.2, then 
~~~
# deletefb -E ### -P ### -U ### -Y 2011 
Traceback (most recent call last):
  File "/home/dominix/.local/bin/deletefb", line 11, in <module>
    load_entry_point('delete-facebook-posts==1.1.2', 'console_scripts', 'deletefb')()
  File "/home/dominix/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/dominix/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/home/dominix/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/home/dominix/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/dominix/.local/lib/python3.6/site-packages/deletefb/deletefb.py", line 13, in <module>
    from .tools.likes import unlike_pages
  File "/home/dominix/.local/lib/python3.6/site-packages/deletefb/tools/likes.py", line 8, in <module>
    LOG = logger(__name__)
  File "/home/dominix/.local/lib/python3.6/site-packages/deletefb/tools/common.py", line 46, in logger
    with open(config_path, "r", encoding="utf-8") as config_file:
FileNotFoundError: [Errno 2] No such file or directory: 'deletefb/logging_conf.json'
~~~

**Comment by weskerfoot** [comment]
Looking into it, thanks!

**Comment by weskerfoot** [comment]
Should be fixed in 1.1.4 now! Thanks for reporting and sorry about the issues! https://github.com/weskerfoot/DeleteFB/pull/59

**Comment by weskerfoot** [comment]
Will leave open until it's confirmed working

**Comment by weskerfoot** [comment]
I think the only lingering issue is that we should probably add an option to disable logging, or point it at a different path
