### ISSUE TITLE
TypeError: attrs only works with new-style classes.

### ISSUE THREAD

**Issue by dannydover** [weskerfoot/DeleteFB#64]
Upon running the run command provided in the readme, I receive the following response:

```
Traceback (most recent call last):
  File "/Users/ddover/Library/Python/2.7/bin/deletefb", line 9, in <module>
    load_entry_point('delete-facebook-posts==1.1.5', 'console_scripts', 'deletefb')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2697, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2370, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2376, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/ddover/Library/Python/2.7/lib/python/site-packages/deletefb/deletefb.py", line 4, in <module>
    from .tools.likes import unlike_pages
  File "/Users/ddover/Library/Python/2.7/lib/python/site-packages/deletefb/tools/likes.py", line 1, in <module>
    from .archive import archiver
  File "/Users/ddover/Library/Python/2.7/lib/python/site-packages/deletefb/tools/archive.py", line 17, in <module>
    @attr.s
  File "/Users/ddover/Library/Python/2.7/lib/python/site-packages/attr/_make.py", line 959, in attrs
    return wrap(maybe_cls)
  File "/Users/ddover/Library/Python/2.7/lib/python/site-packages/attr/_make.py", line 893, in wrap
    raise TypeError("attrs only works with new-style classes.")
TypeError: attrs only works with new-style classes.
```

I installed the script using the "pip install --user delete-facebook-posts" method of installation. I am running MacOS 10.14.5 with the latest version of Chrome installed. I installed Chromedriver using "brew cask install chromedriver".

Any ideas on how to fix this? I have tested selenium and chromedriver with other scripts and they are working fine.

**Comment by weskerfoot** [comment]
The issue is that you used Python 2 instead of Python 3 to install. This should be clarified in the documentation (I initially had said to use pip3 but I don't know how it got changed).

**Comment by weskerfoot** [comment]
Updated docs to use `pip3` as the example again.

**Comment by weskerfoot** [comment]
Updated setup.py to force Python 3.6 or greater (but it only works if pip 9.0 or greater is installed)

**Comment by dannydover** [comment]
Thank you for your quick turnaround! Your solution did the trick.
