### ISSUE TITLE
Javascript error: Cannot read property 'left' of undefined

### ISSUE THREAD

**Issue by jpoiraud** [weskerfoot/DeleteFB#79]
Hi,

First of all thanks a lot for writing this script 👍

I'm on OSX 10.14.5 + Chrome 76.0.3809.87, I've installed the script and chromedriver as recommended (option 1 + brew).

The script runs well but after trying to delete the first Facebook post it stops with a javascript error (see below for full info) : "selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot read property 'left' of undefined"

Thanks in adv. for your help :-)
Brgds.
Jerome

```
MacBook-Air-de-Jerome:bin jerome$ ./deletefb -E XXX -P XXX -U https://www.facebook.com/XXX

Two-Factor Auth is enabled.
Please file an issue at https://github.com/weskerfoot/DeleteFB/issues if you run into any problems
        
Pausing to enter 2FA code
Continuing execution
Archiving Post(content='', comments=[], date='2 h', name='3ac193744d5a4d239d55f7143e0c5152')
Traceback (most recent call last):
  File "./deletefb", line 10, in <module>
    sys.exit(run_delete())
  File "/Users/jerome/Library/Python/3.7/lib/python/site-packages/deletefb/deletefb.py", line 110, in run_delete
    year=args.year
  File "/Users/jerome/Library/Python/3.7/lib/python/site-packages/deletefb/tools/wall.py", line 58, in delete_posts
    actions.move_to_element(menu).perform()
  File "/Users/jerome/Library/Python/3.7/lib/python/site-packages/selenium/webdriver/common/action_chains.py", line 80, in perform
    self.w3c_actions.perform()
  File "/Users/jerome/Library/Python/3.7/lib/python/site-packages/selenium/webdriver/common/actions/action_builder.py", line 76, in perform
    self.driver.execute(Command.W3C_ACTIONS, enc)
  File "/Users/jerome/Library/Python/3.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/jerome/Library/Python/3.7/lib/python/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot read property 'left' of undefined
  (Session info: chrome=76.0.3809.87)

```

**Comment by weskerfoot** [comment]
I can confirm. Looks like something has changed that broke it recently. I'll try to take a look as soon as possible, thanks!

**Comment by weskerfoot** [comment]
@jpoiraud I believe I've fixed it. I'll do a new release soon. Thanks for reporting!

**Comment by weskerfoot** [comment]
@jpoiraud Please upgrade to `v1.1.9` and see if your issue is solved, thanks again!

**Comment by jpoiraud** [comment]
@weskerfoot yes it works :-) Thanks a lot !

**Comment by jadejadewei** [comment]
Hi all, I got the same error msg, what do I upgrade to v1.1.9? Thanks

**Comment by weskerfoot** [comment]
> Hi all, I got the same error msg, what do I upgrade to v1.1.9? Thanks

`pip3 install --user delete-facebook-posts==1.1.9` should work.
