### ISSUE TITLE
Chrome binary location should be configurable

### ISSUE THREAD

**Issue by weskerfoot** [weskerfoot/DeleteFB#99]
Did do what you mentionned

Executed the script
Got this:

Downloading Chrome Webdriver
100% |####################################################################################################################################|
DONE!
Traceback (most recent call last):
  File "/Users/nicolas/Library/Python/3.7/bin/deletefb", line 10, in <module>
    sys.exit(run_delete())
  File "/Users/nicolas/Library/Python/3.7/lib/python/site-packages/deletefb/deletefb.py", line 105, in run_delete
    two_factor_token=args.two_factor_token
  File "/Users/nicolas/Library/Python/3.7/lib/python/site-packages/deletefb/tools/login.py", line 41, in login
    driver = setup_selenium(driver_path, chrome_options)
  File "/Users/nicolas/Library/Python/3.7/lib/python/site-packages/deletefb/tools/chrome_driver.py", line 52, in setup_selenium
    return webdriver.Chrome(executable_path=driver_path, options=options)
  File "/Users/nicolas/Library/Python/3.7/lib/python/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/Users/nicolas/Library/Python/3.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Users/nicolas/Library/Python/3.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Users/nicolas/Library/Python/3.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/nicolas/Library/Python/3.7/lib/python/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary

May be I am not installing the app correctly and globally ... Where should the chrome binary be ?

_Originally posted by @nottavi in https://github.com/weskerfoot/DeleteFB/issues/95#issuecomment-569897059_

**Comment by weskerfoot** [comment]
https://github.com/weskerfoot/DeleteFB/issues/95#issuecomment-569911512
